sources:
  - name: "WHO – General Wellness & Healthy Living"
    type: "public_guidance"
    scope: "hydration, nutrition, physical activity, sleep, stress"
  - name: "Public Health Heat Safety Guidance"
    type: "public_guidance"
    scope: "heat exhaustion, heat stroke prevention"
  - name: "Seasonal Influenza (Flu) – Public Information"
    type: "public_guidance"
    scope: "why/when to vaccinate, high-risk groups"
  - name: "Medicine-Use Safety Leaflets (General)"
    type: "public_guidance"
    scope: "read labels, interactions, storage, consult pharmacist"
  - name: "Oman – Emergency Services"
    type: "local_services"
    scope: "emergency number, when to call, what to say"
